### ISSUE TITLE
Add  compile instruction to compile  profile-bee?

### ISSUE THREAD

**Issue by vincentmli** [zz85/profile-bee#5]
Hi,

Could you add instruction to compile profile-bee, sorry totally newbie to rust here :)

**Comment by tippexs** [comment]
Hi @vincentmli all you need to do is mentioned here.
https://github.com/zz85/profile-bee#development

In case you are not familiar with `cargo` and friends you should read something about in the rust book. Let me drop a link.
https://doc.rust-lang.org/cargo/

**Comment by vincentmli** [comment]
@tippexs thanks for the reply, I had this error

   Compiling profile-bee v0.1.0 (/usr/src/profile-bee/profile-bee)
warning: unused import: `ObjItem`
 --> profile-bee/src/process.rs:5:22
  |
5 | use crate::symbols::{ObjItem, StackFrameInfo};
  |                      ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

   Compiling xtask v0.1.0 (/usr/src/profile-bee/xtask)
warning: `profile-bee` (lib) generated 1 warning
error: couldn't read profile-bee/bin/../../target/bpfel-unknown-none/debug/profile-bee: No such file or directory (os error 2)
   --> profile-bee/bin/profile-bee.rs:109:16
    |
109 |     let data = include_bytes_aligned!("../../target/bpfel-unknown-none/debug/profile-bee");
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` which comes from the expansion of the macro `include_bytes_aligned` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused import: `MapRefMut`
 --> profile-bee/bin/profile-bee.rs:2:26
  |
2 | use aya::maps::{HashMap, MapRefMut, Queue, StackTraceMap};
  |                          ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Bpf`
 --> profile-bee/bin/profile-bee.rs:9:53
  |
9 | use aya::{include_bytes_aligned, util::online_cpus, Bpf};
  |                                                     ^^^

warning: unused import: `log::info`
  --> profile-bee/bin/profile-bee.rs:14:5
   |
14 | use log::info;
   |     ^^^^^^^^^

warning: unused import: `signal`
  --> profile-bee/bin/profile-bee.rs:18:13
   |
18 | use tokio::{signal, task};
   |             ^^^^^^

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> profile-bee/bin/profile-bee.rs:109:16
    |
109 |     let data = include_bytes_aligned!("../../target/bpfel-unknown-none/debug/profile-bee");
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: within `Aligned<[u8]>`, the trait `Sized` is not implemented for `[u8]`
note: required because it appears within the type `Aligned<[u8]>`
   --> profile-bee/bin/profile-bee.rs:109:16
    |
109 |     let data = include_bytes_aligned!("../../target/bpfel-unknown-none/debug/profile-bee");
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: structs must have a statically known size to be initialized
    = note: this error originates in the macro `include_bytes_aligned` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
warning: `profile-bee` (bin "profile-bee") generated 4 warnings
error: could not compile `profile-bee` due to 2 previous errors; 4 warnings emitted
warning: build failed, waiting for other jobs to finish...

**Comment by vincentmli** [comment]
root@vli-2004:/usr/src/profile-bee# cargo xtask build-ebpf
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/xtask build-ebpf`
error: "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
       ` rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu` <===THIS corrected the error
thread 'main' panicked at 'assertion failed: status.success()', xtask/src/build_ebpf.rs:62:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@vli-2004:/usr/src/profile-bee#  rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
info: downloading component 'rust-src'
info: installing component 'rust-src'
root@vli-2004:/usr/src/profile-bee# cargo xtask build-ebpf

**Comment by RoySunnySean007** [comment]
I like the profile-bee very much, but failed to compile it...:(
I also encountered the similar error, could u please kindly suggest, @tippexs ?

**cargo build:**
`warning: unused import: `ObjItem`
 --> profile-bee/src/process.rs:5:22
  |
5 | use crate::symbols::{ObjItem, StackFrameInfo};
  |                      ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0308]: mismatched types
   --> profile-bee/src/process.rs:38:41
    |
38  |         let mapper = ProcessMapper::new(maps);
    |                      ------------------ ^^^^ expected `Option<Vec<MemoryMap>>`, found `Option<MemoryMaps>`
    |                      |
    |                      arguments to this function are incorrect
    |
    = note: expected enum `std::option::Option<Vec<MemoryMap>>`
               found enum `std::option::Option<MemoryMaps>`
note: associated function defined here
   --> profile-bee/src/process.rs:103:12
    |
103 |     pub fn new(maps: Option<Vec<MemoryMap>>) -> Option<Self> {
    |            ^^^ ----------------------------

error[E0308]: mismatched types
   --> profile-bee/src/process.rs:109:40
    |
109 |                 ProcessMapper::is_exec(perms)
    |                 ---------------------- ^^^^^ expected `&str`, found `&MMPermissions`
    |                 |
    |                 arguments to this function are incorrect
    |
    = note: expected reference `&str`
               found reference `&MMPermissions`
note: associated function defined here
   --> profile-bee/src/process.rs:118:8
    |
118 |     fn is_exec(flags: &str) -> bool {
    |        ^^^^^^^ -----------

error[E0308]: mismatched types
   --> profile-bee/src/process.rs:110:49
    |
110 |                     && !ProcessMapper::is_write(perms)
    |                         ----------------------- ^^^^^ expected `&str`, found `&MMPermissions`
    |                         |
    |                         arguments to this function are incorrect
    |
    = note: expected reference `&str`
               found reference `&MMPermissions`
note: associated function defined here
   --> profile-bee/src/process.rs:121:8
    |
121 |     fn is_write(flags: &str) -> bool {
    |        ^^^^^^^^ -----------

error[E0308]: mismatched types
   --> profile-bee/src/process.rs:111:47
    |
111 |                     && ProcessMapper::is_read(perms)
    |                        ---------------------- ^^^^^ expected `&str`, found `&MMPermissions`
    |                        |
    |                        arguments to this function are incorrect
    |
    = note: expected reference `&str`
               found reference `&MMPermissions`
note: associated function defined here
   --> profile-bee/src/process.rs:124:8
    |
124 |     fn is_read(flags: &str) -> bool {
    |        ^^^^^^^ -----------

error[E0599]: no method named `expect` found for enum `LookupResult` in the current scope
   --> profile-bee/src/symbols.rs:340:18
    |
335 |               let mut frames = obj
    |  ______________________________-
336 | |                 .ctx
337 | |                 .as_ref()
338 | |                 .unwrap()
339 | |                 .find_frames(self.address())
340 | |                 .expect("find frames");
    | |                 -^^^^^^ method not found in `LookupResult<impl LookupContinuation<Output = Result<FrameIter<'_, EndianReader<RunTimeEndian, Rc<[u8]>>>, Error>, Buf = EndianReader<RunTimeEndian, Rc<[u8]>>>>`
    | |_________________|
    | 

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
warning: `profile-bee` (lib) generated 1 warning
error: could not compile `profile-bee` (lib) due to 5 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...`

**cargo xtask build-ebpf:**
I need to install nightly-x86_64-unknown-linux-gnu toolchain, but after I installed via `rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu`, still have the following error: 

`error: invalid argument
  --> src/main.rs:21:10
   |
21 | #[kprobe(name = "kprobe_profile")]
   |          ^^^^

error: invalid argument
  --> src/main.rs:27:10
   |
27 | #[uprobe(name = "uprobe_profile")]
   |          ^^^^

error: expected `name` and `category` arguments
  --> src/main.rs:34:1
   |
34 | / pub fn tracepoint_profile(ctx: TracePointContext) -> u32 {
35 | |     unsafe { collect_trace(ctx) }
36 | |     0
37 | | }
   | |_^

warning: unused imports: `TracePointContext`, `programs::ProbeContext`
 --> src/main.rs:7:5
  |
7 |     programs::ProbeContext,
  |     ^^^^^^^^^^^^^^^^^^^^^^
8 |     programs::{PerfEventContext, TracePointContext},
  |                                  ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `profile-bee-ebpf` (bin "profile-bee") generated 1 warning
error: could not compile `profile-bee-ebpf` (bin "profile-bee") due to 3 previous errors; 1 warning emitted`

**Comment by ldsys** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
ms-ati, @cmdplusr, @felipek, @bwoods, @anaganisk, @amitdo, @trgoofi, @zhsso, @robertmarsal, @jerry-shao, @haomingz, @ay, @jas-, @ipconfigme, @denis-ivanov, @questor, @tomohiro, @osdjp-lab, @mrluanma, @pcasaretto, @marctmiller, @HuiInIreland, @piotrbulinski, @picatz, @ggrandes, @kt3k, @zhjwpku, @aneutron, @orfix, @argoneus, @hionay, @ryosan-470, @elsbrock, @, @darkdown, @agergo, @zu1k, @null-dev, @jtopjian, @yagop, @6D65, @rsxss, @cieplak, @y-taka-23, @andy, @501st-alpha1, @digipigeon, @vietlq, @hackwaly, @ziwon

**Comment by zz85** [comment]
Hi all, the repository have been updated to work with the latest rust and crates version.

as from the README, try running

```
cargo xtask build-ebpf
cargo xtask run
```

and let me know if you still encounter errors.
